# Generated by Django 5.1.7 on 2026-04-16 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilProfesor',
        ),
    ]
