# Generated by Django 5.1.7 on 2026-04-16 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrevistaTutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('situacion_trabajada', models.TextField()),
                ('fase_motivacional_dominante', models.CharField(choices=[('sin_identificar', 'Sin identificar'), ('precontemplacion', 'Precontemplación'), ('contemplacion', 'Contemplación'), ('preparacion', 'Preparación'), ('accion', 'Acción'), ('mantenimiento', 'Mantenimiento')], default='sin_identificar', max_length=30)),
                ('dimension_academica', models.BooleanField(default=False)),
                ('dimension_socioemocional', models.BooleanField(default=False)),
                ('dimension_identitaria', models.BooleanField(default=False)),
                ('dimension_vincular', models.BooleanField(default=False)),
                ('dimension_proyeccion', models.BooleanField(default=False)),
                ('desarrollo_sesion', models.TextField(blank=True)),
                ('meta_concreta', models.TextField()),
                ('compromiso_tutor', models.TextField()),
                ('criterio_profesional', models.CharField(choices=[('continua_tutoria', 'Continúa tutoría'), ('mesa_de_casos', 'Mesa de casos'), ('derivacion', 'Derivación')], max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas_tutoria', to='students.estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas_tutoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
    ]
