# Generated by Django 5.1.7 on 2026-04-15 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('curso', models.CharField(max_length=50)),
                ('correo_apoderado', models.EmailField(blank=True, max_length=254)),
                ('telefono_apoderado', models.CharField(blank=True, max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['curso', 'apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='RegistroImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('registros_exitosos', models.PositiveIntegerField(default=0)),
                ('registros_error', models.PositiveIntegerField(default=0)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Importación',
                'verbose_name_plural': 'Registros de Importación',
                'ordering': ['-fecha_importacion'],
            },
        ),
    ]
